#Email Class:
#Formats SOS events into emails and sends them to a reciepiant
class Email
  
   attr_accessor :sender      #The email sender (email address)
   attr_accessor :sender_name #An alias for the sender
   attr_accessor :subject     #The email subject
   attr_accessor :body        #The email body
   attr_accessor :hostname    #The name of the computer sending the email
   attr_accessor :recepiant   #The recepiant email address
	attr_accessor :cc_list     #cc list for email "user@one.com,user@two.com"
   attr_accessor :domain      #The email domin

   #Initialize email constants
   def initialize(du,du_path,domain)
      @hostname = `hostname`.chomp!
      @recepiant = du_path.owner+"@"+domain
      @subject = "Disk Usage Warning: #{@hostname}"
		@sender = "root@#{@hostname}"
      @sender_name = "SimulationDiskspace"
		@body = "*"*10+" Disk Usage Warning! "+"*"*10
		if du.df.cc_list
			@cc_list = du.df.cc_list
		else
			@cc_list = false
		end
		body << %&

You are using #{du_path.size}G of disk space:
\t#{@hostname} 
\t#{du_path.path}

The current threshold for this email warning is #{du.limit.to_s}Gb.
Please remove data immediatly!
Failure to do so may result in loss of simulation data for yourself and other users.

Hard Drive Info:
\tFilesystem - #{du.df.filesystem}
\tUsage - #{du.df.used}%


************************************************************
Generated by Du
************************************************************

&

   end

   #Send the email
   def send()
      #Old "mail" command, modified to use mailx
      #command = "echo \"#{@body}\" | mail -s \"#{@subject}\" #{recepiant} -- -F #{@sender_name} -f #{@sender} "
      if @cc_list
         cc_cmd = "-c \"#{@cc_list}\" "
      else
         cc_cmd = ""
      end
      
      command = "echo \"#{@body}\" | mailx -s \"#{@subject}\" #{cc_cmd} -r #{@sender} #{recepiant} "
      if $DUVERBOSE; puts command; end;
      if !$DUNOEMAIL
         result = `#{command}`
         if $DUVERBOSE
            puts "Email Sent"
            puts result
         end
      end
   end


end
